{{ if .Values.mxcore.jwtSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  jwt_secret: {{ .Values.mxcore.jwtSecret.secret | b64enc }}
{{- end }}
